fix(coreos-c10n): Allow empty user-data to be used for c10n service

diff --git a/bin/coreos-c10n b/bin/coreos-c10n
--- a/bin/coreos-c10n
+++ b/bin/coreos-c10n
@@ -15,62 +15,61 @@ BOOTSTRAP_DISCOVERY="/var/run/etcd/bootstrap.disco"
 
 /usr/bin/block-until-url $META_URL
 
-# Attempt to download userdata, exiting on failure or no user-data is found
+# Attempt to download userdata, exiting on failure
 USER_DATA=$(curl -s --fail $META_URL/user-data)
+retcode=$?
 
-if [ $? -ne 0 ]; then
+if [ $retcode -ne 0 ] && [ $retcode -ne 22 ]; then
 	echo "Unable to communicate with EC2 metadata service"
 	exit 1
-	
-elif [ -z "${USER_DATA}" ]; then
-	echo "No user-data provided"
-	exit 0
 fi
 
 # Preserve the original user-data contents to use as the c10n token in case
 # a discovery URL is not provided.
 C10N_TOKEN="${USER_DATA}"
 
-# If user-data is an HTTPS url, follow it
-if echo "${USER_DATA}" | grep -q '^https://'; then
-	# Backwards compatibility.  If we have a GitHub gist that doesn't end in /raw, we'll append it to before grabbing the gist
-	if echo "${USER_DATA}" | grep -e '^https://gist.github.com' | grep -v -e 'raw$'; then
-		USER_DATA="${USER_DATA}/raw"
+if [ -n "${USER_DATA}" ]; then
+	# If user-data is an HTTPS url, follow it
+	if echo "${USER_DATA}" | grep -q '^https://'; then
+		# Backwards compatibility.  If we have a GitHub gist that doesn't end in /raw, we'll append it to before grabbing the gist
+		if echo "${USER_DATA}" | grep -e '^https://gist.github.com' | grep -v -e 'raw$'; then
+			USER_DATA="${USER_DATA}/raw"
+		fi
+
+		echo "Downloading contents of URL: ${USER_DATA}"
+
+		USER_DATA="$(curl -s $USER_DATA)"
 	fi
 
-	echo "Downloading contents of URL: ${USER_DATA}"
+	# Create temporary file that gets cleaned up on exit
+	TMP=$(mktemp)
+	trap "rm -f ${TMP}" EXIT
 
-	USER_DATA="$(curl -s $USER_DATA)"
-fi
+	# Write user-data to disk for future validation
+	echo "${USER_DATA}" > $TMP
 
-# Create temporary file that gets cleaned up on exit
-TMP=$(mktemp)
-trap "rm -f ${TMP}" EXIT
+	# If user-data is a script, execute it
+	if  head -n 1 $TMP | grep -q '^#!'; then
+		echo "Executing user-data as script"
+		chmod +x $TMP
+		$TMP
 
-# Write user-data to disk for future validation
-echo "${USER_DATA}" > $TMP
+		if grep -q '^ETCD_DISCOVERY_URL=' $TMP; then
+			eval $(grep  '^ETCD_DISCOVERY_URL=' $TMP | tail -n1)
+		fi
 
-# If user-data is a script, execute it
-if  head -n 1 $TMP | grep -q '^#!'; then
-	echo "Executing user-data as script"
-	chmod +x $TMP
-	$TMP
+		if grep -q '^START_FLEET=1' $TMP; then
+			START_FLEET=1
+		fi
 
-	if grep -q '^ETCD_DISCOVERY_URL=' $TMP; then
-		eval $(grep  '^ETCD_DISCOVERY_URL=' $TMP | tail -n1)
-	fi
+	# Validate the user-data as an SSH key, installing it if so
+	else
+		# This just validates the key
+		ssh-keygen -l -f $TMP > /dev/null 2>&1
 
-	if grep -q '^START_FLEET=1' $TMP; then
-		START_FLEET=1
-	fi
-
-# Validate the user-data as an SSH key, installing it if so
-else
-	# This just validates the key
-	ssh-keygen -l -f $TMP > /dev/null 2>&1
-
-	if [ $? -eq 0 ]; then
-		update-ssh-keys -a c10n $TMP
+		if [ $? -eq 0 ]; then
+			update-ssh-keys -a c10n $TMP
+		fi
 	fi
 fi
 
@@ -78,8 +77,9 @@ fi
 if [ -n "${ETCD_DISCOVERY_URL}"  ]; then
 	echo "Using '${ETCD_DISCOVERY_URL}' as etcd discovery url"
 	echo "${ETCD_DISCOVERY_URL}" > $BOOTSTRAP_DISCOVERY
+
 # ...otherwise, we treat the provided user-data as a legacy c10n URL
-elif [ -n "${C10N_TOKEN}" ]; then
+else
 	echo "Using '$C10N_TOKEN' as c10n token"
 
 	# Assert we have networking up and able to access the c10n service
